export default {
  docs: [
    {
      type: "autogenerated",
      dirName: ".", // docs/
    }, // ad sits after the last real nav item
//     {
//       type: "html",
//       value: `
//         <div
//       style="
//         max-width: 260px;
//         margin: 3px auto 16px auto;
//         font-size: 13px;
// margin-top: 20px;
//         color: #407ec9;
//         background-color: hsl(0, 0%, 98%);
//         box-shadow: 0 1px 4px 1px hsla(0, 0%, 0%, 0.1);
//       "
//     >
//       <a
//         href="https://emailengine.app/?utm_source=nodemailer&utm_campaign=nodemailer&utm_medium=sidebar"
//         style="
//           display: inline-block;
//           color: #407ec9;
//           text-decoration: none;
//           font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen-Sans, Ubuntu, Cantarell, 'Helvetica Neue', Helvetica, Arial, sans-serif;
//         "
//       >
//         <div style="display: flex; align-items: center; gap: 5px; width: 100%; background: white" target="_blank">
//           <div style="flex-basis: 50%">
//             <img src="/img/EmailEngine_logo_vert.png" style="width: 130px" />
//           </div>
//           <div style="flex-basis: 50%">
//             <div style="font-size: 13px; line-height: 1.5; text-align: left">使用 OAuth2 轻松通过 Outlook 和 Gmail 收发邮件。</div>
//           </div>
//         </div>
//       </a>
//     </div>
//       `,
//       defaultStyle: false, // keeps Docusaurus from restyling it as a list item
//     },
  ],
};
